export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';



// USER QUEST LOGIC
export const LOAD_USER_QUESTS = "LOAD_USER_QUESTS";
export const CLEAR_USER_QUESTS = "CLEAR_USER_QUESTS";
export const LOAD_USER_QUEST = "LOAD_USER_QUEST";
export const CLEAR_USER_QUEST = "CLEAR_USER_QUEST";
export const LOAD_USER_QUEST_ERROR = "LOAD_USER_QUEST_ERROR";
export const DELETE_USER_QUEST = "DELETE_USER_QUEST"
export const LOAD_USER_QUEST_PAGE = "LOAD_USER_QUEST_PAGE";
export const CLEAR_USER_QUEST_PAGE = "CLEAR_USER_QUEST_PAGE";


// QUEST USER PAGE LOGIC
export const SHOW_ELEMENT = "SHOW_ELEMENT";
export const VALIDATE_ELEMENT = "VALIDATE_ELEMENT";
export const COMPLETE_ELEMENT = "COMPLETE_ELEMENT";
export const ELEMENT_ERROR = "ELEMENT_ERROR";
export const GET_HINT = "GET_HINT";


// CREATE QUEST LOGIC
export const LOAD_QUESTS_CREATED = "LOAD_QUESTS_CREATED";
export const CREATE_QUEST = "CREATE_QUEST";
export const DELETE_QUEST = "DELETE_QUEST";
export const ADD_QUEST_PAGE = "ADD_NEW_QUEST_PAGE";
export const REMOVE_QUEST_PAGE = "REMOVE_QUEST_PAGE";

export const ADD_ELEMENT = "ADD_ELEMENT";
export const DELETE_ELEMENT = "DELETE_ELEMENT";
export const UPDATE_ELEMENT = "UPDATE_ELEMENT";
export const REORDER_ELEMENTS = "REORDER_ELEMENTS";


export const SHARE_QUEST = "SHARE_QUEST";